[tool.poetry]
name = "os-presence"
version = "0.1.0"
description = ""
authors = ["MannuVilasara <mannuvilasara@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pypresence = "^4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
